# Generated by Django 3.1 on 2020-09-04 01:14

import FileImport.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftype', models.CharField(choices=[('MPR', 'Monthly Participation Report - MPR'), ('RRIEP', 'Reverse Referral & Individual Employment Plan (RRIEP)'), ('DISENROLL', 'Disenrollment/Job Placement Report')], default=FileImport.enums.FileImportTypes['MPR'], help_text='Excel File Type Import:', max_length=32)),
                ('file_path', models.CharField(help_text='Path of file to be imported including the file name', max_length=200)),
                ('import_parameters', models.CharField(blank=True, help_text='parameters of the import is a dictionary stored as json.loads string', max_length=200, null=True)),
                ('period', models.CharField(blank=True, help_text='file upload period in weeks or months etc..', max_length=36, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User executing the import', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
