# Generated by Django 3.1.1 on 2020-09-09 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0012_remove_agency_programs"),
        ("FileImport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileimport",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                help_text="Agency for which the import is executed, typically User's agency.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="agency.agency",
            ),
        ),
    ]
