# Generated by Django 3.1.1 on 2020-09-17 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FileImport', '0004_fileimport_xls_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileimport',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='fileimport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
