# Generated by Django 3.1.1 on 2020-09-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FileImport", "0005_auto_20200917_1012"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fileimport",
            options={
                "verbose_name": "Data Import Log",
                "verbose_name_plural": "Data Import Logs",
            },
        ),
        migrations.AlterField(
            model_name="fileimport",
            name="file_path",
            field=models.CharField(
                blank=True,
                help_text="Path of file to be imported including the file name (if not attached directly via XLS file field)",
                max_length=200,
                null=True,
            ),
        ),
    ]
