# Generated by Django 3.0.8 on 2020-08-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0005_auto_20200817_1217"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="address",
        ),
        migrations.AddField(
            model_name="clientaddress",
            name="client",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="client.Client",
            ),
        ),
    ]
