# Generated by Django 3.0.8 on 2020-08-19 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20200817_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientaddress',
            old_name='address',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='clientaddress',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.ClientAddress'),
        ),
    ]
