# Generated by Django 3.1 on 2020-08-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0007_auto_20200819_0616"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
    ]
