# Generated by Django 3.1.1 on 2020-09-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0009_auto_20200903_1111"),
        ("client", "0002_auto_20200903_1814"),
    ]

    operations = []
