# Generated by Django 3.1.1 on 2020-09-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0010_merge_20200909_0538"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientaddress",
            options={
                "verbose_name": "Client Address",
                "verbose_name_plural": "Client Addresses",
            },
        ),
    ]
