# Generated by Django 3.1.1 on 2020-09-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20200914_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
    ]
