# Generated by Django 3.1.1 on 2020-09-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_remove_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='client.client'),
        ),
    ]
