# Generated by Django 3.1.1 on 2020-09-21 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0004_auto_20200914_1958"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="effective_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
