# Generated by Django 3.1.1 on 2020-09-21 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0005_note_effective_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="effective_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
