# Generated by Django 3.1.1 on 2020-09-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_remove_agency_programs'),
        ('eligibility', '0007_auto_20200914_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityqueue',
            name='requestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.agency'),
        ),
    ]
