# Generated by Django 3.1 on 2020-09-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20200817_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='program.enrollment')),
            ],
            options={
                'db_table': 'program_enrollment_service',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='program.enrollment')),
            ],
            options={
                'db_table': 'program_enrollment_activity',
                'ordering': ['id'],
            },
        ),
    ]
