# Generated by Django 3.1.1 on 2020-09-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0014_auto_20200911_0602"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentservice",
            name="service_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollment_services",
                to="program.enrollmentservicetype",
            ),
        ),
    ]
