# Generated by Django 3.1.1 on 2020-09-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0016_auto_20200914_1914"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programeligibility",
            name="client",
        ),
        migrations.RemoveField(
            model_name="programeligibility",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="programeligibility",
            name="program",
        ),
        migrations.DeleteModel(
            name="HistoricalProgramEligibility",
        ),
        migrations.DeleteModel(
            name="ProgramEligibility",
        ),
    ]
