# Generated by Django 3.1.1 on 2020-09-28 09:10

import core.json_yaml_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0017_auto_20200924_0733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentservice",
            name="values",
            field=core.json_yaml_field.JsonYamlField(blank=True, null=True),
        ),
    ]
