# Generated by Django 3.1 on 2020-08-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20200826_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='respondent_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='respondent_type',
        ),
        migrations.AlterField(
            model_name='response',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='responses', to='client.client'),
        ),
    ]
