# Generated by Django 3.1 on 2020-08-19 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iep", "0003_auto_20200818_0942"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientiep",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientiep",
            name="projected_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientiep",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientiep",
            name="case_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="iep",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
