# Generated by Django 3.0.8 on 2020-08-20 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0005_auto_20200814_1022'),
        ('iep', '0005_clientiep_eligibility_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientiep',
            name='eligibility_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eligibility.EligibilityQueue'),
        ),
    ]
