# Generated by Django 3.1 on 2020-08-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iep', '0006_auto_20200820_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientiep',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='clientiepenrollment',
            options={'ordering': ['id']},
        ),
    ]
