name: Python application

on:
  push:
    branches:
      - master
      - ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install system libraries
        run: sudo apt-get install python-dev libpq-dev
      - name: Install postgress
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "11"
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --system
      - name: Test
        run: |
          pwd
          cd src
          pytest -x
        env:
          DATABASE_URL: postgres://postgres@db:5432/postgres
# on:
#     push:
#       branches:
#         - master

#   name: Deploy to GSNAP server

#   jobs:

#     deploy:
#       name: Deploy
#       runs-on: ubuntu-latest

#       steps:
#       - name: Checkout
#         uses: actions/checkout@v1

#   #     - name: Configure AWS credentials
#   #       uses: aws-actions/configure-aws-credentials@v1
#   #       with:
#   #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   #         aws-region: us-east-2

#       - name: Build
#         uses: actions/setup-node@v1
#         with:
#           node-version: '10.x'

#       - run: npm install
#       - run: DCI_SERVER_URL=http://213.184.8.117:8002 npm run build # DCI_SERVER_URL is required to read site config

#       - uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --acl public-read --follow-symlinks # --delete
#         env:
#           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
#           SOURCE_DIR: 'dist'      # optional: defaults to entire repository
#           DEST_DIR: 'dci-test'
